# This is a basic workflow to help you get started with Actions

name: Update Notes Site

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Clone Site
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          rm -rf ./NotesWebsite/content/notes/
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/cykna/NotesWebsite.git
          ls -a --recursive
          cp -r . ./NotesWebsite/content/notes/
      - name: Push to site repo 
        run: |
          cd site-das-notas
          git add .
          git commit -m "Atualização automática das notas via GitHub Actions" || echo "Nada para commitar"
          git push origin main
